### ISSUE TITLE
2 phases state value, not in the list of options provided

### ISSUE THREAD

**Issue by maccan-tech** [sockless-coding/garo_wallbox#53]
`Logger: homeassistant
Source: components/sensor/__init__.py:636
First occurred: September 16, 2024 at 19:10:54 (347 occurrences)
Last logged: 06:42:54

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/garo_wallbox/base.py", line 27, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 636, in state
    raise ValueError(
ValueError: Sensor sensor.garo_laddbox_phases provides state value '2', which is not in the list of options provided`

**Comment by sockless-coding** [comment]
@maccan-tech interesting, didn't know that was a possible state...
What type of charger/setup do you have that supports two phase power?

**Comment by maccan-tech** [comment]
@sockless-coding 
I have a GLBDCWM-T222FC.
And when my wife is charging here Skoda Citigo it only charges at 7kw and only on 2 phases.

You where fast, i was prepering to make a pullrequest :-)
Dont forgot changes to the icons.json file.

**Comment by sockless-coding** [comment]
Yeah, I forgot the icon, I'll fix that so it gets included in the next release :)

Good to know, I thought Type 2 only supported 1 or 3 phase charging
